client_id = "58ea0d7b99ede672681e64adb1daeabf"
name = "hoymiles-chat"
application_url = "https://marina-definitely-sim-flows.trycloudflare.com"
embedded = true

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [
  "https://marina-definitely-sim-flows.trycloudflare.com/auth/callback"
]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
prefix = "apps"
subpath = "chat"
url = "https://marina-definitely-sim-flows.trycloudflare.com"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]